[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E", "F", "B", "D", "I"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.ruff.pydocstyle]
convention = "google"